application: mystical-banner-139818
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F4_1G # B1 - 128MB; 600Mhz; $0.05 / B2 - 256MB; 1.2Ghz; $0.10 / B4 - 512MB; 2.4Ghz; $0.20 / B4_1G - 1024MB; 2.4Ghz; $0.30 / B8 - 1024MB; 4.8Ghz; $0.40
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 50ms
  max_pending_latency: automatic
  max_concurrent_requests: 8

builtins:
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.APP